---
kind: pipeline
type: docker
name: ARM64 Build

platform:
  os: linux
  arch: arm64

steps:
- name: Build PR
  when:
    event:
      - pull_request
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: ghcr.io/rmb938/xen-orchestra-ce-arm64
    dry_run: true
    tags:
      - ${DRONE_COMMIT_SHA:0:8}

- name: Build Tag
  when:
    event:
      - tag
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: ghcr.io/rmb938/xen-orchestra-ce-arm64
    username: rmb938
    password:
      from_secret: docker_password
    tags:
      - ${DRONE_TAG}

---
kind: pipeline
type: docker
name: AMD64 Build

platform:
  os: linux
  arch: amd64

steps:
- name: Build PR
  when:
    event:
      - pull_request
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: ghcr.io/rmb938/xen-orchestra-ce-amd64
    dry_run: true
    tags:
      - ${DRONE_COMMIT_SHA:0:8}

- name: Build Tag
  when:
    event:
      - tag
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: ghcr.io/rmb938/xen-orchestra-ce-amd64
    username: rmb938
    password:
      from_secret: docker_password
    tags:
      - ${DRONE_TAG}
